apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "staj2026.fullname" . }}-config
  labels:
    {{- include "staj2026.labels" . | nindent 4 }}
data:
  SPRING_DATASOURCE_URL: >-
    jdbc:postgresql://{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}