apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "staj2026.fullname" . }}-postgres-pvc
  labels:
    {{- include "staj2026.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.storage }}