apiVersion: v1
kind: Secret
metadata:
  name: {{ include "staj2026.fullname" . }}-secret
  labels:
    {{- include "staj2026.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: {{ .Values.database.username | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.database.password | quote }}
  JWT_SECRET: {{ .Values.jwt.secret | quote }}