spring.application.name=staj2026

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/staj2026}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=validate

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=${SPRING_LIQUIBASE_ENABLED:true}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET}
jwt.expiration=3600000

# Elasticsearch
spring.elasticsearch.uris=${ELASTICSEARCH_URL:http://localhost:9200}

# Couchbase
spring.couchbase.connection-string=${COUCHBASE_CONNECTION_STRING:couchbase://localhost}
spring.couchbase.username=${COUCHBASE_USERNAME:Administrator}
spring.couchbase.password=${COUCHBASE_PASSWORD:}
spring.data.couchbase.bucket-name=${COUCHBASE_BUCKET:staj2026}
