server:
  port: 8081

spring:
  application:
    name: staj2026-gateway
  data:
    redis:
      host: ${VALKEY_HOST:localhost}
      port: ${VALKEY_PORT:6379}

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: staj2026-api
              uri: ${BACKEND_URL:http://localhost:8080}
              predicates:
                - Path=/api/**

management:
  endpoints:
    web:
      exposure:
        include: health,info

