apiVersion: v1
kind: Service
metadata:
  name: staj2026-app-service
spec:
  selector:
    app: staj2026-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: staj2026-app
spec:
  replicas: 1

  selector:
    matchLabels:
      app: staj2026-app

  template:
    metadata:
      labels:
        app: staj2026-app

    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:17
          command:
            - sh
            - -c
            - |
              until pg_isready -h postgres -p 5432 -U postgres -d staj2026;
              do
                echo "Waiting for PostgreSQL..."
                sleep 3
              done

      containers:
        - name: staj2026-app
          image: staj2026-app:ci
          imagePullPolicy: Never

          ports:
            - containerPort: 8080

          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/staj2026

            - name: SPRING_DATASOURCE_USERNAME
              value: postgres

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: staj2026-secrets
                  key: postgres-password

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: staj2026-secrets
                  key: jwt-secret