apiVersion: v1
kind: Secret
metadata:
  name: staj2026-postgres-secret
type: Opaque
stringData:
  postgres-password: postgres

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: staj2026-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: staj2026-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: staj2026-postgres
spec:
  serviceName: postgres
  replicas: 1

  selector:
    matchLabels:
      app: staj2026-postgres

  template:
    metadata:
      labels:
        app: staj2026-postgres

    spec:
      containers:
        - name: postgres
          image: postgres:17

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_DB
              value: staj2026

            - name: POSTGRES_USER
              value: postgres

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: staj2026-postgres-secret
                  key: postgres-password

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data

          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
                - -d
                - staj2026
            initialDelaySeconds: 10
            periodSeconds: 5

      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: staj2026-postgres-pvc