global_defs {
    router_id HA_NODE_1
    script_user root
    enable_script_security
}

vrrp_script check_haproxy {
    script "/usr/bin/pgrep haproxy"
    interval 2
    weight -60
    fall 2
    rise 2
}

vrrp_instance VI_1 {
    state MASTER
    interface eth0
    virtual_router_id 45
    priority 150
    advert_int 1

    unicast_src_ip 192.168.104.3
    unicast_peer {
        192.168.104.1
    }

    authentication {
        auth_type PASS
        auth_pass staj2026
    }

    virtual_ipaddress {
        192.168.104.100/24 dev eth0
    }

    track_script {
        check_haproxy
    }
}
